### Get access token with normal user

POST http://localhost:8180/realms/mineral/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=backend&client_secret=bQG1f1VFFPbGkF8sjtMPryOXQChtU8p4&username=zamlamb&password=admin&grant_type=password&scope=openid

//saving the access token
> {%
    client.global.set("access_token", response.body.access_token);
%}




### Valid Request APPOINTMENT
POST http://localhost:8090/api/make-appointment
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "sellerId": "5c2db01b-1b71-48be-8b93-fa25635a388d",
  "licensePlate": "ABC-123",
  "materialType": "PET_COKE",
  "appointmentWindowStart": "2024-10-30T09:00:00",
  "appointmentWindowEnd": "2024-10-30T10:00:00"
}





### Unauthorized Request APPOINTMENT
POST http://localhost:8090/api/make-appointment/5c2db01b-1b71-48be-8b93-fa25635a388d/5c2db01b-1b71-48be-8b93-fa25635a388d/ABC-123/PET_COKE/2024-10-30T09:00:00/2024-10-30T10:00:00

### Bad Request APPOINTMENT: Start date is after end date
POST http://localhost:8090/api/make-appointment/5c2db01b-1b71-48be-8b93-fa25635a388d/ABC-123/PET_COKE/2024-10-30T10:00:00/2024-10-30T09:00:00
Authorization: Bearer {{access_token}}

### Invalid material type APPOINTMENT
POST http://localhost:8090/api/make-appointment/5c2db01b-1b71-48be-8b93-fa25635a388d/ABC-123/INVALID_MATERIAL/2024-10-30T09:00:00/2024-10-30T10:00:00
Authorization: Bearer {{access_token}}

### Empty license plate APPOINTMENT
POST http://localhost:8090/api/make-appointment/5c2db01b-1b71-48be-8b93-fa25635a388d//PET_COKE/2024-10-30T09:00:00/2024-10-30T10:00:00
Authorization: Bearer {{access_token}}

### Post of  docktruck and need to insert the warehouse information
###
POST http://localhost:8090/api/dock-truck
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "licensePlate": "ABC-123",
  "materialType": "PET_COKE",
  "warehouseId": "e2f7bcdc-69da-4b0e-b73f-6adf79e8d5f9",
  "sellerId": "dd2e2b7d-4622-441f-9200-123f8bb3e29b",
  "deliveryDate": "2024-10-30T09:00:00",
  "dockNumber": "WB-10",
  "weight": 111
}


### Receive Warehouse Number and Weighbridge
POST http://localhost:8090/api/receive-warehouse-number
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "licensePlate": "ABC-123",
  "materialType": "PET_COKE",
  "sellerId": "dd2e2b7d-4622-441f-9200-123f8bb3e29b"
}


### Recognize Truck
POST http://localhost:8090/api/recognize-truck
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "licensePlate": "ABC-123",
  "materialType": "PET_COKE",
  "dockNumber": "WB-10"
}

