spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/mineral/protocol/openid-connect/certs
          issuer-uri: http://localhost:8180/realms/mineral


