server:
  port: ${PORT:8090}
  servlet:
    context-path: /api


spring:
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: "jdbc:mysql://localhost:3306/app_db"
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword

  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/mineral/protocol/openid-connect/certs
          issuer-uri: http://localhost:8180/realms/mineral

logging:
  level:
    web: DEBUG
